version: "3.9"

services:
  app:
    build: ./backend
    container_name: exam-seating-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - exam-net

  nginx:
    build: ./frontend
    container_name: exam-seating-frontend
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - exam-net

networks:
  exam-net:
    driver: bridge
